name: "TODO Issue Creator"
on: ["push"]
jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@master"
      - name: "TODO to Issue"
        uses: "alstr/todo-to-issue-action@v3.0.2-beta"
        id: "Type: Todo"
        with:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}